Add Cypress tests for Devices page
astarte-platform/astarte-dashboard pull request #187
Opened 2020-09-29 12:38 UTC by davidebriani

This PR adds basic UI tests to ensure the Devices page is rendered correctly

2020-09-29 15:56 UTC, Pavinati approved these changes

2020-09-30 16:34 UTC, Pavinati requested changes

2020-09-30 16:34 UTC, Pavinati commented on cypress/integration/devices_page_test.js
> +      cy.fixture('devices').as('devices');
this represents a detailed device list, let's use a more specific name, for example `device_list_detailed` or `detailed_devices` to name a couple. Normally when queering for Astarte devices, you only obtain a list of IDs.
We can still save the fixture as `devices` though

2020-09-30 16:34 UTC, Pavinati commented on cypress/fixtures/devices.json
> +  "data": [
we could add one or two more devices, even if with fewer data. Take for example a device that just got registered, but never connected to astarte

2020-10-01 09:00 UTC, Pavinati approved these changes

2020-10-01 09:27 UTC, bettio approved these changes

2020-10-01 09:27 UTC, merged