Add Cypress tests for New Flow creation
astarte-platform/astarte-dashboard pull request #201
Opened 2020-10-05 12:46 UTC by davidebriani

This PR adds basic checks in Cypress to make sure the New Flow page correctly handles interactions to create a new flow

2020-10-06 16:29 UTC, Pavinati requested changes

2020-10-06 16:29 UTC, Pavinati commented on cypress/fixtures/pipeline.room-occupation.json
> +    "source": "astarte_devices_source\n    .realm(${$.config.realm})\n    .amqp_exchange(${$.config.amqp_exchange})\n    .target_devices(${$.config.devices})\n| filter\n    .script(\"\"\"\n
this data contains references to organizations. Lets keep it clean and replace those references with fake names and URLs

2020-10-07 07:58 UTC, Pavinati approved these changes

2020-10-07 15:34 UTC, bettio approved these changes

2020-10-07 15:34 UTC, merged