Add typescript for Interfaces page
astarte-platform/astarte-dashboard pull request #214
Opened 2020-10-09 16:29 UTC by davidebriani

This PR adds Typescript's types to Interfaces page.

2020-10-15 16:17 UTC, Pavinati requested changes

2020-10-15 16:17 UTC, Pavinati commented on src/astarte-client/client.ts
> +    return response.data.sort();
adding a sort here changes the behavior of the api. I don't think the client should sort the data, that should be done by the view/screen if they ever need to.

2020-10-19 14:09 UTC, Pavinati approved these changes

2020-10-20 09:42 UTC, bettio approved these changes

2020-10-20 09:43 UTC, merged