main.scss: fix device pie chart on Chrome
astarte-platform/astarte-dashboard pull request #223
Opened 2020-10-14 15:32 UTC by Pavinati

By default chrome renders the chart with minimum height,
setting height to 100% makes it expand as much as it is allowed.

Signed-off-by: Mattia Pavinati <mattia.pavinati@ispirata.com>

2020-10-14 16:48 UTC, davidebriani commented on src/static/styles/main.scss
> +  height: 100%;
Now it shows up in Chrome. But when you have a long list of interfaces, the graph drifts away from its legend/labels:

![Screenshot_20201014_184609](https://user-images.githubusercontent.com/60540759/96020008-b234af80-0e4d-11eb-84ae-fc640c26fd4b.png)

2020-10-15 13:25 UTC, davidebriani approved these changes

2020-10-15 15:25 UTC, bettio requested changes

2020-10-15 15:25 UTC, bettio commented on CHANGELOG.md
> +- Device sent data pie chart now showing up on Chrome browser.
`Exchanged bytes pie chart`

2020-10-15 15:44 UTC, bettio approved these changes

2020-10-15 15:45 UTC, merged