Enhance AstarteToken validation
astarte-platform/astarte-dashboard pull request #246
Opened 2020-11-30 18:48 UTC by davidebriani

This PR adds validation via JWT checks and Yup to check whether a valid encoded string is supplied.
The AstarteToken class will now also parse the regular expressions contained in the token's claims in order to later check available authorizations in a simple way.

2020-12-01 10:32 UTC, Pavinati approved these changes

2020-12-02 14:58 UTC, bettio requested changes
Is it possible to merge this in 1.0?

2020-12-02 15:20 UTC, Pavinati commented
closed by mistake

2020-12-17 12:25 UTC, bettio approved these changes

2020-12-17 12:25 UTC, merged