Double encode group names in Astarte API URLs
astarte-platform/astarte-dashboard pull request #254
Opened 2020-12-16 14:55 UTC by Pavinati

make sure percent and slash character are properly encoded in API URLs

Signed-off-by: Mattia <mattia.pavinati@ispirata.com>

2020-12-16 15:13 UTC, davidebriani requested changes

2020-12-16 15:13 UTC, davidebriani commented on cypress/integration/group_page_test.js
> +    it.only('correctly removes a device from a group with symbols in its name', function () {
You forgot to remove `.only` from test definition

2020-12-16 15:13 UTC, davidebriani commented on cypress/integration/group_page_test.js
> +        }).as('deleteDeviceCheck');
I think `deleteDeviceRequest` might be a better naming here than `deleteDeviceCheck`, following the pattern we already used in other test files.

2020-12-16 15:13 UTC, davidebriani commented on src/elm/AstarteApi.elm
> +        , url = buildUrl apiConfig.secureConnection apiConfig.appengineUrl [ "v1", apiConfig.realm, "groups", encodedGroupName, "devices" ] []
Do you think it could be useful to add a test for this `addDeviceToGroup` API too?

2020-12-17 15:18 UTC, davidebriani approved these changes

2020-12-18 16:37 UTC, bettio approved these changes

2020-12-18 16:37 UTC, merged