consider ValueChange triggers on path /* as invalid
astarte-platform/astarte-dashboard pull request #268
Opened 2021-01-21 14:02 UTC by Pavinati

Show error feedback on data trigger path when trigger is
ValueChange and path /*
See also https://github.com/astarte-platform/astarte/issues/513

Signed-off-by: Mattia <mattia.pavinati@ispirata.com>

2021-01-21 14:31 UTC, bettio requested changes

2021-01-21 14:31 UTC, bettio commented on src/elm/Page/TriggerBuilder.elm
> +    -- TODO this is a workaround, reenable ValueChange after being fixed in Astarte
re-enable

2021-01-21 14:31 UTC, bettio commented on CHANGELOG.md
> +- Disable ValueChanged, ValueChangedApplied triggers on /* paths
... (workaround to ref-to-issue-here)

2021-01-21 16:19 UTC, bettio approved these changes

2021-01-21 16:26 UTC, rbino requested changes

2021-01-21 16:26 UTC, rbino commented on CHANGELOG.md
> +- Disable ValueChanged and ValueChangedApplied triggers on /* paths
Typo: ValueChange and ValueChangeApplied

2021-01-21 16:26 UTC, rbino commented on src/elm/Page/TriggerBuilder.elm
> +        matchesInterface =
I'm not sure about the name of this variable, maybe `matchesMapping` is better?

2021-01-25 10:38 UTC, rbino approved these changes

2021-01-25 10:39 UTC, bettio approved these changes

2021-01-25 10:39 UTC, merged