Support target device or group in data triggers
astarte-platform/astarte-dashboard pull request #274
Opened 2021-01-27 18:02 UTC by davidebriani

This PR adds options in the TriggerEditor to be able to specify a target device or target group even for data triggers.
This feature corresponds to setting a specific `device_id` or `group_name` in a Trigger's JSON form when its `type` equals `data_trigger`. For more details, see [the documentation](https://docs.astarte-platform.org/1.0/060-triggers.html#data-triggers).

2021-02-04 16:27 UTC, Pavinati requested changes

2021-02-04 16:27 UTC, Pavinati commented on src/elm/Types/DataTrigger.elm
> +    let
didn't test it, but this is the way to go
```
let
    resultValue =
        case maybeKnownValue of
            Just ( value, jType ) ->
                Ok (value, jType)

            Nothing ->
                Err "some error....."

    resultTarget =
        case ( groupName, deviceId ) of
            ( "*", "*" ) ->
                Ok AllDevices

            ( _, "*" ) ->
                Ok (DeviceGroup groupName)

            ( "*", _ ) ->
                Ok (SpecificDevice deviceId)

            ( _, _ ) ->
                Err "Cannot have both device ID and group name"
in
case ( resultValue, resultTarget ) of
    ( Ok (knownValue, knownValueType), Ok target ) ->
        Decode.succeed (DataTrigger iName iMajor on path operator knownValue knownValueType target)

    ( Err msg, _ ) ->
        Decode.fail msg

    ( _, Err msg ) ->
        Decode.fail msg
```

2021-02-04 18:09 UTC, davidebriani commented on src/elm/Types/DataTrigger.elm
> +    let
Nice, that's more like it. I admit I struggled a bit with Elm not knowing how to properly exploit conditionals/pattern matching.
I directly copied your snippet and it works fine, thanks!

2021-02-05 17:11 UTC, davidebriani commented on src/elm/Page/TriggerBuilder.elm
> +renderDataTriggerTargetSelect editMode target =
I tried to extract the methods like you did in your snippet. However the resulting code just seems more convoluted, not to mention I still need to pattern match on `DataTrigger.Target` types with related arguments.
Therefore I would leave the code as it is, if you're ok with it.

2021-02-05 17:14 UTC, Pavinati commented on src/elm/Page/TriggerBuilder.elm
> +renderDataTriggerTargetSelect editMode target =
We're removing this piece of code soon anyway, so it's ok :+1: 
Plus it's just 3 options. The code is still pretty easy to read

2021-02-05 17:15 UTC, Pavinati approved these changes

2021-02-08 10:27 UTC, bettio approved these changes

2021-02-08 10:27 UTC, merged