Fix validation of database_retention_ttl in blocks schema
astarte-platform/astarte-dashboard pull request #282
Opened 2021-02-03 11:28 UTC by davidebriani

This PR fixes JSON Schema of blocks with proper values for `database_retention_ttl`, avoiding the property to default to 0 which is invalid.

2021-02-03 11:30 UTC, rbino requested changes

2021-02-03 11:30 UTC, rbino commented on src/astarte-client/definitions/blocks/virtual_device_pool.json
> +            "minimum": 60,
There's actually also a maximum
https://github.com/astarte-platform/astarte_core/blob/master/lib/astarte_core/mapping.ex#L91

2021-02-03 11:30 UTC, rbino commented on src/astarte-client/definitions/blocks/dynamic_virtual_device_pool.json
> +            "minimum": 60,
There's actually also a maximum
https://github.com/astarte-platform/astarte_core/blob/master/lib/astarte_core/mapping.ex#L91

2021-02-05 10:55 UTC, rbino approved these changes

2021-02-08 10:28 UTC, bettio approved these changes

2021-02-08 10:29 UTC, merged