Fix login layout on small screen devices
astarte-platform/astarte-dashboard pull request #290
Opened 2021-02-19 13:04 UTC by Pavinati

![image](https://user-images.githubusercontent.com/5071605/108507982-67bfb580-72bb-11eb-890e-32229bfed2b7.png)

2021-02-19 13:58 UTC, davidebriani approved these changes

2021-02-19 17:50 UTC, bettio commented on CHANGELOG.md
> +- Login layout on small screen devices.
@rbino any suggestion about how to rephrase this?

2021-02-19 17:50 UTC, bettio requested changes
I think we should rephrase the changelog entry

2021-02-23 14:46 UTC, bettio approved these changes

2021-02-23 14:46 UTC, merged