Forward port release-1.0 into master
astarte-platform/astarte-dashboard pull request #293
Opened 2021-02-25 11:21 UTC by davidebriani

2021-02-25 17:45 UTC, Pavinati requested changes

2021-02-25 17:45 UTC, Pavinati commented on CHANGELOG.md
> +## [1.0.0-beta.2] - Unreleased
this is wrong, [Unreleased] contains the changelog of master (where we reworked the interface editor)
`## [1.0.0-beta.2] - Unreleased` is where changed the login layout

2021-02-26 12:43 UTC, Pavinati requested changes
maybe we should add a linter rule for that (eol-last)

2021-02-26 12:43 UTC, Pavinati commented on cypress/integration/blocks_page_test.js
> +});
missing newline

2021-02-26 12:43 UTC, Pavinati commented on cypress/integration/device_page_test.js
> +});
missing newline

2021-02-26 14:32 UTC, Pavinati approved these changes

2021-02-26 17:10 UTC, bettio approved these changes

2021-02-26 17:10 UTC, merged