Use device attributes instead of metadata
astarte-platform/astarte-dashboard pull request #305
Opened 2021-03-22 17:27 UTC by Pavinati

Parse device attributes field in place of removed metadata field

Signed-off-by: Mattia <mattia.pavinati@ispirata.com>

2021-03-23 14:08 UTC, davidebriani requested changes

2021-03-23 14:08 UTC, davidebriani commented on src/elm/Page/Device.elm
> +                newAttribute =
`newAttribute` -> `newAttributes`

2021-03-23 14:08 UTC, davidebriani commented on src/elm/Page/Device.elm
> +                newAttribute =
`newAttribute` -> `newAttributes`

2021-03-23 14:08 UTC, davidebriani commented on src/elm/Page/Device.elm
> +                    , deviceAttributeCard device Card.HalfWidth
`deviceAttributeCard` -> `deviceAttributesCard`

2021-03-23 14:08 UTC, davidebriani commented on src/elm/Page/Device.elm
> +        Card.simpleText "Device has no attribute"
`renderAttribute` -> `renderAttributes`
`attribute` -> `attributes`

2021-03-23 14:08 UTC, davidebriani commented on src/elm/Types/Device.elm
> +encodeAttribute attributes =
`encodeAttribute` -> `encodeAttributes`

2021-03-23 14:08 UTC, davidebriani commented on src/react/DevicesPage.tsx
> +  attribute: AstarteDevice['attributes'];
`attribute` -> `attributes`

2021-03-23 14:08 UTC, davidebriani commented on src/react/DevicesPage.tsx
> +const MatchedAttribute = ({
`MatchedAttribute` -> `MatchedAttributes`
`MatchedAttributeProps` -> `MatchedAttributesProps`

2021-03-23 14:08 UTC, davidebriani commented on src/elm/AstarteApi.elm
>          }
`updateDeviceAttribute ... attribute ...` -> `updateDeviceAttributes ... attributes ...`
`Device.encodeAttribute attribute` -> `Device.encodeAttributes attributes`

2021-03-23 16:38 UTC, davidebriani approved these changes

2021-03-24 16:12 UTC, bettio requested changes

2021-03-24 16:12 UTC, bettio commented on CHANGELOG.md
> +- Parse device Attributes field in place of removed Metadata field.
I don't like it, this is uninteresting for users. "- Device metadata are called device attributes now. Astarte >= 1.0.0-beta.2 is required."

2021-03-24 16:16 UTC, bettio approved these changes

2021-03-24 16:16 UTC, merged