Add Redux state management
astarte-platform/astarte-dashboard pull request #307
Opened 2021-03-25 09:09 UTC by davidebriani

This change adds the boilerplate setup to create a Redux store, as an organized mean to cache and share global state.
An initial store slice is also created to cache the list of Blocks and share it across pages.

2021-03-25 11:36 UTC, Pavinati requested changes

2021-03-25 11:36 UTC, Pavinati commented on src/store/index.ts
> +};
`BlocksState` is imported by `./blocks` and `StoreState` is used by the same file. That would generate a circular dependency between files. The compiler handles that just fine, but logically this shouldn't happen.
Are we forcefully splitting code that should be in the same file?

2021-03-25 11:36 UTC, Pavinati commented on src/store/blocks.ts
> +  status: 'empty',
'empty` is an invalid state that represents that we did not retrieve the blocks from the Astarte API.
While in this state, no action should be allowed except loading blocks.
If that initial loading fails, you end up in the error state with a null value for blocks.

What about starting in a "valid" initial state? Like `ok` and empty list of blocks?

2021-03-25 11:36 UTC, Pavinati commented on src/store/blocks.ts
> +  get: createAsyncThunk('blocks/get', (name: string, { extra }) =>
If this the **Blocks** state, should we add getters for single blocks too?
Not sure, but i think it's worth splitting the single block from the collection of blocks.

2021-03-25 11:36 UTC, Pavinati commented on src/store/index.ts
> +const createStore = (astarte: AstarteClient) =>
This smells like premature optimization. Let's write a specific store first, and if in the future we will need a generic store, we can create something that fits all the specific stores requirements.

2021-04-09 15:20 UTC, Pavinati approved these changes

2021-04-09 16:36 UTC, bettio approved these changes

2021-04-12 11:43 UTC, bettio approved these changes

2021-04-12 11:43 UTC, merged