Filter modal to only display endpoints with set values
astarte-platform/astarte-dashboard pull request #458
Opened 2024-08-16 14:25 UTC by safeta87

Updated the modal to display only the endpoints
that have set values

2024-08-19 09:23 UTC, Pavinati requested changes

2024-08-19 09:23 UTC, Pavinati commented on src/DeviceInterfaceValues.tsx
> +  const [endpoints, setEndpoints] = useState<string[]>([]);
`endpoints` is too generic here. Which kind of endpoint are those? All the endpoints? only the ones with some data? only the ones that can be unset?

2024-08-19 09:23 UTC, Pavinati commented on src/DeviceInterfaceValues.tsx
> +      };
similarly here, `matchesPattern` is a bit misleading, This function doesn't just match a pattern, it first modifies it, then matches it from start to finish.
I suggest making it more explicit, like
```typescript
const matchMapping = (endpoint: string, mapping: AstarteMapping): boolean => {
  const endpointPattern = mapping.endpoint.replace(/%\{[^}]+\}/g, '[^/]+');
  const endpointRegex = new RegExp(`^${endpointPattern}$`);
  return endpointRegex.test(endpoint);
};

[...]

            mappingsWithUnsetAllowed.some((mapping) =>
              matchMapping(property.endpoint, mapping),
            )
```
Remember this is a pure function, so it's best declared outside of the React component (let's declare it just before `UnsetDataModalProps`)

2024-08-26 10:02 UTC, davidebriani requested changes

2024-08-26 10:02 UTC, davidebriani commented on src/DeviceInterfaceValues.tsx
>                <option value="">Select an endpoint</option>
I would disable this option, the user shouldn't be able to select it.

```suggestion
              <option value="" disabled>Select an endpoint</option>
```

2024-08-26 10:29 UTC, davidebriani approved these changes

2024-08-26 10:40 UTC, merged